"""UUIDv7 generation (Physical DB PD-01: "Primary keys are UUIDv7, generated by the owning
module in the application layer; no database-side PK default on business tables. PG17 has no
native uuidv7(); app generation keeps the 'owning module creates the id' rule literal.").

RFC 9562 layout (48-bit ms timestamp | 4-bit version | 12-bit rand_a | 2-bit variant | 62-bit
rand_b): monotonically time-ordered for index locality, unguessable within a millisecond.
"""

from __future__ import annotations

import os
import time
from uuid import UUID


def uuid7() -> UUID:
    unix_ts_ms = int(time.time() * 1000)
    rand = os.urandom(10)

    ts_bytes = unix_ts_ms.to_bytes(6, byteorder="big")

    rand_a = int.from_bytes(rand[0:2], byteorder="big") & 0x0FFF  # 12 bits
    rand_b = int.from_bytes(rand[2:10], byteorder="big") & 0x3FFFFFFFFFFFFFFF  # 62 bits

    version_and_rand_a = (0x7 << 12) | rand_a  # version nibble = 0111
    variant_and_rand_b = (0b10 << 62) | rand_b  # variant bits = 10

    value = (
        int.from_bytes(ts_bytes, byteorder="big") << 80
        | version_and_rand_a << 64
        | variant_and_rand_b
    )
    return UUID(int=value)
