"""Static parity check between `identity.infrastructure.persistence.models` (the ORM source of
truth) and the hand-written migration `3aec1ec32ea3_identity_create_user_account_.py` (see that
file's own docstring for why it is hand-written rather than autogenerated). Catches the class of
drift a schema change to `models.py` without a matching migration edit would introduce, without
needing to execute DDL against a real database (that is covered separately by
`integration/test_repository_live.py`, which exercises the ORM-mapped schema against real
Postgres, and by the manual `alembic upgrade`/`downgrade` verification recorded in this module's
README/traceability notes).
"""

from __future__ import annotations

from identity.infrastructure.persistence.base import IdentityBase
from identity.infrastructure.persistence.models import (
    AuthenticationMethodRow,
    OtpChallengeRow,
    OutboxEventRow,
    ProcessedEventRow,
    RoleAssignmentRow,
    UserAccountRow,
)

EXPECTED_TABLES = {
    "user_account",
    "authentication_method",
    "role_assignment",
    "otp_challenge",
    "outbox_event",
    "processed_event",
}

EXPECTED_COLUMNS = {
    "user_account": {
        "id",
        "phone",
        "email",
        "display_name",
        "status",
        "phone_reveal_mode",
        "notify_email",
        "notify_web_push",
        "notify_sms",
        "owned_profile_ids",
        "account_kind",
        "anketa",
        "review_status",
        "review_decision_outcome",
        "review_decision_reason",
        "review_decision_reviewer_id",
        "review_decision_decided_at",
        "created_at",
        "updated_at",
        "lock_version",
    },
    "authentication_method": {
        "id",
        "account_id",
        "method_type",
        "identifier",
        "verified_at",
        "added_at",
        "password_hash",
    },
    "role_assignment": {
        "id",
        "account_id",
        "role_definition_head_id",
        "role_definition_version_id",
        "role_code",
        "acting_profile_id",
        "assigned_at",
        "assigned_by",
    },
    "otp_challenge": {
        "id",
        "phone",
        "purpose",
        "code_hash",
        "attempts",
        "max_attempts",
        "ip_address",
        "created_at",
        "expires_at",
        "consumed_at",
    },
    "outbox_event": {
        "id",
        "event_type",
        "occurred_at",
        "actor",
        "aggregate_type",
        "aggregate_id",
        "aggregate_version",
        "payload",
        "dispatch_status",
        "attempts",
        "dispatched_at",
        "created_at",
    },
    "processed_event": {"event_id", "handler", "processed_at", "result"},
}


def test_identity_schema_registers_exactly_the_expected_tables() -> None:
    assert set(IdentityBase.metadata.tables.keys()) == {
        f"identity.{name}" for name in EXPECTED_TABLES
    }


def test_every_mapped_table_has_the_expected_columns() -> None:
    for model in (
        UserAccountRow,
        AuthenticationMethodRow,
        RoleAssignmentRow,
        OtpChallengeRow,
        OutboxEventRow,
        ProcessedEventRow,
    ):
        table = model.__table__
        expected = EXPECTED_COLUMNS[table.name]
        actual = {c.name for c in table.columns}
        assert actual == expected, f"{table.name}: expected {expected}, got {actual}"


def test_user_account_has_partial_unique_indexes_on_phone_and_email() -> None:
    table = UserAccountRow.__table__
    index_names = {ix.name for ix in table.indexes}
    assert "ux_user_account_phone" in index_names
    assert "ux_user_account_email" in index_names


def test_processed_event_has_composite_primary_key() -> None:
    pk_columns = {c.name for c in ProcessedEventRow.__table__.primary_key.columns}
    assert pk_columns == {"event_id", "handler"}
