"""contracts.events -- the complete, frozen v1 domain-event catalogue (DDD Sec 6)."""

from __future__ import annotations

from contracts.events.ads import (
    BannerCampaignEnded,
    BannerCampaignScheduled,
    BannerCampaignStarted,
    BannerClickRecorded,
    BannerImpressionRecorded,
)
from contracts.events.analytics import AuditEntryRecorded, MetricEventCaptured
from contracts.events.billing import (
    EntitlementActivated,
    EntitlementExpired,
    EntitlementRevoked,
    InvoiceIssued,
    OrderPlaced,
    PaymentConfirmed,
)
from contracts.events.catalog import (
    ContactButtonClicked,
    FavoriteAdded,
    FavoriteRemoved,
    ListingArchived,
    ListingCreated,
    ListingDeleted,
    ListingDraftSaved,
    ListingEdited,
    ListingExpired,
    ListingFlagged,
    ListingPublished,
    ListingRenewed,
    ListingSuspended,
    ListingViewed,
    PremiumListingStat,
)
from contracts.events.configuration import (
    CategoryChanged,
    CategoryCreated,
    CategoryRetired,
    ConfigurationChanged,
    FormDefinitionPublished,
    NotificationTemplateChanged,
    PlacementSlotDefined,
    PlatformSettingsChanged,
    ProductDefinitionChanged,
    RoleDefinitionChanged,
    SearchConfigurationChanged,
)
from contracts.events.identity import AccountClosed, AccountSuspended, UserRegistered
from contracts.events.media import MediaAssetAccepted, MediaAssetReady, MediaAssetRejected
from contracts.events.messaging import (
    ChatInitiated,
    ContentReported,
    MessageSent,
    PhoneRevealed,
    UserBlocked,
)
from contracts.events.moderation import ModerationActionTaken
from contracts.events.profiles import (
    BusinessProfileCreated,
    BusinessVerified,
    VerificationRejected,
    VerificationRequested,
    VerifiedBadgeExpired,
)
from shared_kernel import EventEnvelope

EVENT_CATALOGUE: dict[str, type[EventEnvelope]] = {
    "UserRegistered": UserRegistered,
    "AccountSuspended": AccountSuspended,
    "AccountClosed": AccountClosed,
    "BusinessProfileCreated": BusinessProfileCreated,
    "VerificationRequested": VerificationRequested,
    "BusinessVerified": BusinessVerified,
    "VerificationRejected": VerificationRejected,
    "VerifiedBadgeExpired": VerifiedBadgeExpired,
    "ListingCreated": ListingCreated,
    "ListingDraftSaved": ListingDraftSaved,
    "ListingPublished": ListingPublished,
    "ListingEdited": ListingEdited,
    "ListingSuspended": ListingSuspended,
    "ListingArchived": ListingArchived,
    "ListingDeleted": ListingDeleted,
    "ListingExpired": ListingExpired,
    "ListingRenewed": ListingRenewed,
    "ListingFlagged": ListingFlagged,
    "FavoriteAdded": FavoriteAdded,
    "FavoriteRemoved": FavoriteRemoved,
    "ListingViewed": ListingViewed,
    "ContactButtonClicked": ContactButtonClicked,
    "PremiumListingStat": PremiumListingStat,
    "MediaAssetAccepted": MediaAssetAccepted,
    "MediaAssetReady": MediaAssetReady,
    "MediaAssetRejected": MediaAssetRejected,
    "ConfigurationChanged": ConfigurationChanged,
    "CategoryCreated": CategoryCreated,
    "CategoryChanged": CategoryChanged,
    "CategoryRetired": CategoryRetired,
    "FormDefinitionPublished": FormDefinitionPublished,
    "ProductDefinitionChanged": ProductDefinitionChanged,
    "PlacementSlotDefined": PlacementSlotDefined,
    "RoleDefinitionChanged": RoleDefinitionChanged,
    "SearchConfigurationChanged": SearchConfigurationChanged,
    "NotificationTemplateChanged": NotificationTemplateChanged,
    "PlatformSettingsChanged": PlatformSettingsChanged,
    "OrderPlaced": OrderPlaced,
    "InvoiceIssued": InvoiceIssued,
    "PaymentConfirmed": PaymentConfirmed,
    "EntitlementActivated": EntitlementActivated,
    "EntitlementExpired": EntitlementExpired,
    "EntitlementRevoked": EntitlementRevoked,
    "BannerCampaignScheduled": BannerCampaignScheduled,
    "BannerCampaignStarted": BannerCampaignStarted,
    "BannerCampaignEnded": BannerCampaignEnded,
    "BannerImpressionRecorded": BannerImpressionRecorded,
    "BannerClickRecorded": BannerClickRecorded,
    "ChatInitiated": ChatInitiated,
    "MessageSent": MessageSent,
    "UserBlocked": UserBlocked,
    "PhoneRevealed": PhoneRevealed,
    "ContentReported": ContentReported,
    "ModerationActionTaken": ModerationActionTaken,
    "MetricEventCaptured": MetricEventCaptured,
    "AuditEntryRecorded": AuditEntryRecorded,
}
"""event_type string -> event class, for the "no event missing, no event invented" check.
Covers exactly DDD Sec 6's table, as amended by ADR-0001 (docs/adr/0001-media-asset-status-events.md,
adding the three BC-06 events DDD Sec 6's published table omitted) and ADR-0005
(docs/adr/0005-analytics-missing-metric-events.md, adding the three BC-03 metric events DDD Sec
6's published table also omitted despite Sec 5.13's own 8-key closed vocabulary naming them) --
see contracts/tests/test_event_catalogue.py."""

__all__ = [
    "EVENT_CATALOGUE",
    "AccountClosed",
    "AccountSuspended",
    "AuditEntryRecorded",
    "BannerCampaignEnded",
    "BannerCampaignScheduled",
    "BannerCampaignStarted",
    "BannerClickRecorded",
    "BannerImpressionRecorded",
    "BusinessProfileCreated",
    "BusinessVerified",
    "CategoryChanged",
    "CategoryCreated",
    "CategoryRetired",
    "ChatInitiated",
    "ConfigurationChanged",
    "ContactButtonClicked",
    "ContentReported",
    "EntitlementActivated",
    "EntitlementExpired",
    "EntitlementRevoked",
    "FavoriteAdded",
    "FavoriteRemoved",
    "FormDefinitionPublished",
    "InvoiceIssued",
    "ListingArchived",
    "ListingCreated",
    "ListingDeleted",
    "ListingDraftSaved",
    "ListingEdited",
    "ListingExpired",
    "ListingFlagged",
    "ListingPublished",
    "ListingRenewed",
    "ListingSuspended",
    "ListingViewed",
    "MediaAssetAccepted",
    "MediaAssetReady",
    "MediaAssetRejected",
    "MessageSent",
    "MetricEventCaptured",
    "ModerationActionTaken",
    "NotificationTemplateChanged",
    "OrderPlaced",
    "PaymentConfirmed",
    "PhoneRevealed",
    "PlacementSlotDefined",
    "PlatformSettingsChanged",
    "PremiumListingStat",
    "ProductDefinitionChanged",
    "RoleDefinitionChanged",
    "SearchConfigurationChanged",
    "UserBlocked",
    "UserRegistered",
    "VerificationRejected",
    "VerificationRequested",
    "VerifiedBadgeExpired",
]
