"""Static parity check between `catalog.infrastructure.persistence.models` (the ORM source of
truth) and the hand-written migration `c9f482b269ed_catalog_create_listing_schema.py` (see that
file's own docstring for why it is hand-written rather than autogenerated). Mirrors
`apps/backend/tests/media/test_models.py`'s pattern exactly. Also the DM-02 "no EAV table exists"
proof the P-07 prompt explicitly requires."""

from __future__ import annotations

from catalog.infrastructure.persistence.base import CatalogBase
from catalog.infrastructure.persistence.models import (
    FavoriteRow,
    ImageAttachmentRow,
    ListingRow,
    ListingTransitionRow,
    OutboxEventRow,
    ProcessedEventRow,
    SubscriptionProjectionRow,
)

EXPECTED_TABLES = {
    "listing",
    "image_attachment",
    "listing_transition",
    "favorite",
    "subscription_projection",
    "outbox_event",
    "processed_event",
}

EXPECTED_COLUMNS = {
    "listing": {
        "id",
        "listing_type",
        "owner_user_id",
        "owner_profile_id",
        "category_id",
        "category_path",
        "form_definition_id",
        "form_definition_version_id",
        "title",
        "description",
        "attribute_document",
        "price_amount",
        "price_currency",
        "location_lat",
        "location_long",
        "lifecycle_state",
        "is_flagged",
        "awaiting_payment",
        "expires_at",
        "published_at",
        "promotion_kind",
        "promotion_valid_until",
        "promotion_entitlement_id",
        "slug",
        "created_at",
        "updated_at",
        "lock_version",
    },
    "image_attachment": {
        "id",
        "listing_id",
        "media_asset_id",
        "position",
        "asset_status_snapshot",
        "created_at",
    },
    "listing_transition": {
        "id",
        "listing_id",
        "from_state",
        "to_state",
        "transition_kind",
        "actor_user_id",
        "reason",
        "occurred_at",
    },
    "favorite": {"id", "user_id", "listing_id", "created_at"},
    "subscription_projection": {
        "owner_profile_id",
        "entitlement_id",
        "product_definition_id",
        "quota_document",
        "valid_until",
        "source_event_id",
    },
    "outbox_event": {
        "id",
        "event_type",
        "occurred_at",
        "actor",
        "aggregate_type",
        "aggregate_id",
        "aggregate_version",
        "payload",
        "dispatch_status",
        "attempts",
        "dispatched_at",
        "created_at",
    },
    "processed_event": {"event_id", "handler", "processed_at", "result"},
}

_MODELS = (
    ListingRow,
    ImageAttachmentRow,
    ListingTransitionRow,
    FavoriteRow,
    SubscriptionProjectionRow,
    OutboxEventRow,
    ProcessedEventRow,
)


def test_catalog_schema_registers_exactly_the_expected_tables() -> None:
    assert set(CatalogBase.metadata.tables.keys()) == {
        f"catalog.{name}" for name in EXPECTED_TABLES
    }


def test_every_mapped_table_has_the_expected_columns() -> None:
    for model in _MODELS:
        table = model.__table__
        expected = EXPECTED_COLUMNS[table.name]
        actual = {c.name for c in table.columns}
        assert actual == expected, f"{table.name}: expected {expected}, got {actual}"


def test_DM02_no_eav_table_exists() -> None:
    """DM-02: "the AttributeSet is one typed JSONB document on `listing`, not an EAV table" --
    there is no `listing_attribute`/`attribute_value`-shaped table anywhere in catalog's schema,
    and `listing.attribute_document` is the one JSONB column carrying it."""
    table_names = {name.split(".", 1)[1] for name in CatalogBase.metadata.tables}
    assert not any("attribute" in name and name != "listing" for name in table_names)
    assert "attribute_document" in {c.name for c in ListingRow.__table__.columns}


def test_no_gin_index_on_attribute_document() -> None:
    """Physical DB "catalog schema" section: "NO GIN index on the AttributeSet document" --
    faceting/filtering on attributes is BC-05/search's job."""
    for index in ListingRow.__table__.indexes:
        assert "attribute_document" not in {c.name for c in index.columns}


def test_image_attachment_has_listing_position_unique_constraint() -> None:
    constraint_names = {c.name for c in ImageAttachmentRow.__table__.constraints}
    assert "ux_image_attachment_listing_position" in constraint_names


def test_favorite_has_user_listing_unique_constraint() -> None:
    constraint_names = {c.name for c in FavoriteRow.__table__.constraints}
    assert "ux_favorite_user_listing" in constraint_names


def test_subscription_projection_is_keyed_by_owner_profile_id_alone() -> None:
    pk_columns = [c.name for c in SubscriptionProjectionRow.__table__.primary_key.columns]
    assert pk_columns == ["owner_profile_id"]


def test_processed_event_has_composite_primary_key() -> None:
    pk_columns = {c.name for c in ProcessedEventRow.__table__.primary_key.columns}
    assert pk_columns == {"event_id", "handler"}
