"""configuration: create eight head+version table pairs, permission_group, outbox_event

Revision ID: 3a5779ed6064
Revises:
Create Date: 2026-07-09 21:36:03.123615

# Message format is "<module>: <verb> <object>" (DevSecOps Sec 7). Expand/contract only:
# additive-first; a destructive operation (DROP TABLE/COLUMN, non-additive TYPE change) needs an
# explicit marker comment `# approved-destructive: <reason>` on the same line, checked by
# tools/check_migration_safety.py (QG-09). An applied migration is never edited (AIR-14) --
# corrections are a new migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from configuration.infrastructure.migrations.version_guard_trigger import (
    drop_version_guard_trigger_ddl,
    version_guard_trigger_ddl,
)

# revision identifiers, used by Alembic.
revision: str = "3a5779ed6064"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = ("configuration",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_category_ck_category_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("code", name="ux_category_code"),
        schema="configuration",
    )
    op.create_table(
        "form_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_form_definition_ck_form_definition_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_definition")),
        sa.UniqueConstraint("code", name="ux_form_definition_code"),
        schema="configuration",
    )
    op.create_table(
        "notification_template",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_notification_template_ck_notification_template_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_template")),
        sa.UniqueConstraint("code", name="ux_notification_template_code"),
        schema="configuration",
    )
    op.create_table(
        "placement_slot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_placement_slot_ck_placement_slot_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placement_slot")),
        sa.UniqueConstraint("code", name="ux_placement_slot_code"),
        schema="configuration",
    )
    op.create_table(
        "platform_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_platform_settings_ck_platform_settings_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_settings")),
        sa.UniqueConstraint("code", name="ux_platform_settings_code"),
        schema="configuration",
    )
    op.create_table(
        "product_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_product_definition_ck_product_definition_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_definition")),
        sa.UniqueConstraint("code", name="ux_product_definition_code"),
        schema="configuration",
    )
    op.create_table(
        "role_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_role_definition_ck_role_definition_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_definition")),
        sa.UniqueConstraint("code", name="ux_role_definition_code"),
        schema="configuration",
    )
    op.create_table(
        "search_configuration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("business_owner", sa.Text(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_search_configuration_ck_search_configuration_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_configuration")),
        sa.UniqueConstraint("code", name="ux_search_configuration_code"),
        schema="configuration",
    )
    op.create_table(
        "outbox_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor", sa.UUID(), nullable=True),
        sa.Column("aggregate_type", sa.String(), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dispatch_status", sa.String(), server_default="PENDING", nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("dispatched_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dispatch_status IN ('PENDING', 'DISPATCHED', 'DEAD')",
            name=op.f("ck_outbox_event_ck_outbox_event_dispatch_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_event")),
        schema="configuration",
    )
    op.create_table(
        "permission_group",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("permission_keys", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission_group")),
        sa.UniqueConstraint("code", name=op.f("ux_permission_group_code")),
        schema="configuration",
    )
    op.create_table(
        "category_version",
        sa.Column("parent_category_id", sa.UUID(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("form_definition_id", sa.UUID(), nullable=False),
        sa.Column("tree_status", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_category_version_ck_category_version_status"),
        ),
        sa.CheckConstraint(
            "tree_status IN ('ACTIVE','RETIRED')",
            name=op.f("ck_category_version_ck_category_version_tree_status"),
        ),
        sa.CheckConstraint(
            "parent_category_id <> head_id",
            name=op.f("ck_category_version_ck_category_version_no_self_parent"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_category_version_ck_category_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["form_definition_id"],
            ["configuration.form_definition.id"],
            name=op.f("fk_category_version_form_definition"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.category.id"],
            name=op.f("fk_category_version_category"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["configuration.category.id"],
            name="fk_category_version_parent_category",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.category_version.id"],
            name=op.f("fk_category_version_category_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_version")),
        sa.UniqueConstraint("head_id", "version_number", name="ux_category_version_head_version"),
        schema="configuration",
    )
    op.create_table(
        "form_definition_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "jsonb_typeof(definition_document->'fields') = 'array'",
            name=op.f("ck_form_definition_version_ck_form_definition_version_fields_array"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_form_definition_version_ck_form_definition_version_status"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_form_definition_version_ck_form_definition_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.form_definition.id"],
            name=op.f("fk_form_definition_version_form_definition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.form_definition_version.id"],
            name=op.f("fk_form_definition_version_form_definition_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_definition_version")),
        sa.UniqueConstraint(
            "head_id", "version_number", name="ux_form_definition_version_head_version"
        ),
        schema="configuration",
    )
    op.create_table(
        "notification_template_version",
        sa.Column("event_key", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "channel IN ('EMAIL','WEB_PUSH','SMS')",
            name=op.f("ck_notification_template_version_ck_notification_template_version_channel"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_notification_template_version_ck_notification_template_version_status"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_notification_template_version_ck_notification_template_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.notification_template.id"],
            name=op.f("fk_notification_template_version_notification_template"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.notification_template_version.id"],
            name=op.f("fk_notification_template_version_notification_template_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_template_version")),
        sa.UniqueConstraint(
            "head_id", "version_number", name="ux_notification_template_version_head_version"
        ),
        schema="configuration",
    )
    op.create_table(
        "placement_slot_version",
        sa.Column("slot_key", sa.Text(), nullable=False),
        sa.Column("page_zone", sa.Text(), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_placement_slot_version_ck_placement_slot_version_status"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_placement_slot_version_ck_placement_slot_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.placement_slot.id"],
            name=op.f("fk_placement_slot_version_placement_slot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.placement_slot_version.id"],
            name=op.f("fk_placement_slot_version_placement_slot_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placement_slot_version")),
        sa.UniqueConstraint(
            "head_id", "version_number", name="ux_placement_slot_version_head_version"
        ),
        schema="configuration",
    )
    op.create_table(
        "platform_settings_version",
        sa.Column("settings_scope", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_platform_settings_version_ck_platform_settings_version_status"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_platform_settings_version_ck_platform_settings_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.platform_settings.id"],
            name=op.f("fk_platform_settings_version_platform_settings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.platform_settings_version.id"],
            name=op.f("fk_platform_settings_version_platform_settings_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_settings_version")),
        sa.UniqueConstraint(
            "head_id", "version_number", name="ux_platform_settings_version_head_version"
        ),
        schema="configuration",
    )
    op.create_table(
        "product_definition_version",
        sa.Column("product_type", sa.Text(), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("price_currency", sa.Text(), nullable=False),
        sa.Column("term_days", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "product_type IN ('BANNER_PLACEMENT','FEATURED','PREMIUM','SUBSCRIPTION','TOP_PLACEMENT','VERIFICATION')",
            name=op.f("ck_product_definition_version_ck_product_definition_version_type"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_product_definition_version_ck_product_definition_version_status"),
        ),
        sa.CheckConstraint(
            "price_amount >= 0",
            name=op.f("ck_product_definition_version_ck_product_definition_version_price"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_product_definition_version_ck_product_definition_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.product_definition.id"],
            name=op.f("fk_product_definition_version_product_definition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.product_definition_version.id"],
            name=op.f("fk_product_definition_version_product_definition_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_definition_version")),
        sa.UniqueConstraint(
            "head_id", "version_number", name="ux_product_definition_version_head_version"
        ),
        schema="configuration",
    )
    op.create_table(
        "role_definition_version",
        sa.Column("role_name", sa.Text(), nullable=False),
        sa.Column("permission_keys", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_role_definition_version_ck_role_definition_version_status"),
        ),
        sa.CheckConstraint(
            "cardinality(permission_keys) > 0",
            name=op.f("ck_role_definition_version_ck_role_definition_version_permission_keys"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_role_definition_version_ck_role_definition_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.role_definition.id"],
            name=op.f("fk_role_definition_version_role_definition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.role_definition_version.id"],
            name=op.f("fk_role_definition_version_role_definition_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_definition_version")),
        sa.UniqueConstraint(
            "head_id", "version_number", name="ux_role_definition_version_head_version"
        ),
        schema="configuration",
    )
    op.create_table(
        "search_configuration_version",
        sa.Column("scope_category_id", sa.UUID(), nullable=True),
        sa.Column("promotion_page_cap", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("definition_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validity_from", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("validity_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("rollback_of_version_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','VALIDATION','APPROVAL','PUBLISHED','DEPRECATED','ARCHIVED')",
            name=op.f("ck_search_configuration_version_ck_search_configuration_version_status"),
        ),
        sa.CheckConstraint(
            "promotion_page_cap >= 0",
            name=op.f("ck_search_configuration_version_ck_search_configuration_version_cap"),
        ),
        sa.CheckConstraint(
            "validity_until IS NULL OR validity_until > validity_from",
            name=op.f("ck_search_configuration_version_ck_search_configuration_version_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["configuration.search_configuration.id"],
            name=op.f("fk_search_configuration_version_search_configuration"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rollback_of_version_id"],
            ["configuration.search_configuration_version.id"],
            name=op.f("fk_search_configuration_version_search_configuration_version"),
        ),
        sa.ForeignKeyConstraint(
            ["scope_category_id"],
            ["configuration.category.id"],
            name=op.f("fk_search_configuration_version_category"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_configuration_version")),
        sa.UniqueConstraint(
            "head_id", "version_number", name="ux_search_configuration_version_head_version"
        ),
        schema="configuration",
    )

    # Deferred: current_version_id FKs, added after all version tables exist
    # (Physical DB Sec 2.4 "circular pair resolved in one publish transaction" -- the
    # tables are mutually referential, so autogenerate cannot express both FKs inline).
    op.create_foreign_key(
        op.f("fk_category_category_version"),
        "category",
        "category_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        op.f("fk_form_definition_form_definition_version"),
        "form_definition",
        "form_definition_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        op.f("fk_notification_template_notification_template_version"),
        "notification_template",
        "notification_template_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        op.f("fk_placement_slot_placement_slot_version"),
        "placement_slot",
        "placement_slot_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        op.f("fk_platform_settings_platform_settings_version"),
        "platform_settings",
        "platform_settings_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        op.f("fk_product_definition_product_definition_version"),
        "product_definition",
        "product_definition_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        op.f("fk_role_definition_role_definition_version"),
        "role_definition",
        "role_definition_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        op.f("fk_search_configuration_search_configuration_version"),
        "search_configuration",
        "search_configuration_version",
        ["current_version_id"],
        ["id"],
        source_schema="configuration",
        referent_schema="configuration",
        deferrable=True,
        initially="DEFERRED",
    )

    # Immutability guard triggers (Physical DB Sec 2.4, PD-07): a PUBLISHED version row may
    # only ever move to DEPRECATED/ARCHIVED afterward; every other column is frozen. Value-
    # conditional (depends on OLD.status), so it is *not* backbone.migrations.guard_trigger_ddl
    # (append-only / fixed-mutable-columns only) -- see version_guard_trigger.py's docstring.
    for stmt in version_guard_trigger_ddl("configuration", "category_version"):
        op.execute(stmt)
    for stmt in version_guard_trigger_ddl("configuration", "form_definition_version"):
        op.execute(stmt)
    for stmt in version_guard_trigger_ddl("configuration", "product_definition_version"):
        op.execute(stmt)
    for stmt in version_guard_trigger_ddl("configuration", "placement_slot_version"):
        op.execute(stmt)
    for stmt in version_guard_trigger_ddl("configuration", "role_definition_version"):
        op.execute(stmt)
    for stmt in version_guard_trigger_ddl("configuration", "search_configuration_version"):
        op.execute(stmt)
    for stmt in version_guard_trigger_ddl("configuration", "notification_template_version"):
        op.execute(stmt)
    for stmt in version_guard_trigger_ddl("configuration", "platform_settings_version"):
        op.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> (
    None
):  # approved-destructive: dev-only fresh-install rollback, never run against applied data
    for stmt in drop_version_guard_trigger_ddl("configuration", "category_version"):
        op.execute(stmt)
    for stmt in drop_version_guard_trigger_ddl("configuration", "form_definition_version"):
        op.execute(stmt)
    for stmt in drop_version_guard_trigger_ddl("configuration", "product_definition_version"):
        op.execute(stmt)
    for stmt in drop_version_guard_trigger_ddl("configuration", "placement_slot_version"):
        op.execute(stmt)
    for stmt in drop_version_guard_trigger_ddl("configuration", "role_definition_version"):
        op.execute(stmt)
    for stmt in drop_version_guard_trigger_ddl("configuration", "search_configuration_version"):
        op.execute(stmt)
    for stmt in drop_version_guard_trigger_ddl("configuration", "notification_template_version"):
        op.execute(stmt)
    for stmt in drop_version_guard_trigger_ddl("configuration", "platform_settings_version"):
        op.execute(stmt)

    # Drop the deferred current_version_id FKs first -- each still references its *_version
    # table, which the generated drop-table order below removes before its head.
    op.drop_constraint(
        op.f("fk_category_category_version"), "category", schema="configuration", type_="foreignkey"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_constraint(
        op.f("fk_form_definition_form_definition_version"),
        "form_definition",
        schema="configuration",
        type_="foreignkey",
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_constraint(
        op.f("fk_notification_template_notification_template_version"),
        "notification_template",
        schema="configuration",
        type_="foreignkey",
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_constraint(
        op.f("fk_placement_slot_placement_slot_version"),
        "placement_slot",
        schema="configuration",
        type_="foreignkey",
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_constraint(
        op.f("fk_platform_settings_platform_settings_version"),
        "platform_settings",
        schema="configuration",
        type_="foreignkey",
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_constraint(
        op.f("fk_product_definition_product_definition_version"),
        "product_definition",
        schema="configuration",
        type_="foreignkey",
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_constraint(
        op.f("fk_role_definition_role_definition_version"),
        "role_definition",
        schema="configuration",
        type_="foreignkey",
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_constraint(
        op.f("fk_search_configuration_search_configuration_version"),
        "search_configuration",
        schema="configuration",
        type_="foreignkey",
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        "category_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "form_definition_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "notification_template_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "placement_slot_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "platform_settings_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "product_definition_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "role_definition_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "search_configuration_version", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "permission_group", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "outbox_event", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "category", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "form_definition", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "notification_template", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "placement_slot", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "platform_settings", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "product_definition", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "role_definition", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data
    op.drop_table(
        "search_configuration", schema="configuration"
    )  # approved-destructive: dev-only rollback of this same migration's upgrade(), never run against applied data

    # ### end Alembic commands ###
