"""Static parity check between `media.infrastructure.persistence.models` (the ORM source of
truth) and the hand-written migration `61c1c4e76ca8_media_create_media_asset_image_variant.py`
(see that file's own docstring for why it is hand-written rather than autogenerated). Mirrors
`apps/backend/tests/identity/test_models.py`'s pattern exactly.
"""

from __future__ import annotations

from media.infrastructure.persistence.base import MediaBase
from media.infrastructure.persistence.models import ImageVariantRow, MediaAssetRow, OutboxEventRow

EXPECTED_TABLES = {"media_asset", "image_variant", "outbox_event"}

EXPECTED_COLUMNS = {
    "media_asset": {
        "id",
        "owner_context_type",
        "owner_context_id",
        "storage_key",
        "content_type",
        "size_bytes",
        "scan_status",
        "processing_status",
        "exif_stripped",
        "uploaded_by",
        "created_at",
        "updated_at",
        "lock_version",
    },
    "image_variant": {
        "id",
        "media_asset_id",
        "variant_kind",
        "storage_key",
        "width_px",
        "height_px",
        "size_bytes",
        "created_at",
    },
    "outbox_event": {
        "id",
        "event_type",
        "occurred_at",
        "actor",
        "aggregate_type",
        "aggregate_id",
        "aggregate_version",
        "payload",
        "dispatch_status",
        "attempts",
        "dispatched_at",
        "created_at",
    },
}


def test_media_schema_registers_exactly_the_expected_tables() -> None:
    assert set(MediaBase.metadata.tables.keys()) == {f"media.{name}" for name in EXPECTED_TABLES}


def test_every_mapped_table_has_the_expected_columns() -> None:
    for model in (MediaAssetRow, ImageVariantRow, OutboxEventRow):
        table = model.__table__
        expected = EXPECTED_COLUMNS[table.name]
        actual = {c.name for c in table.columns}
        assert actual == expected, f"{table.name}: expected {expected}, got {actual}"


def test_media_asset_storage_key_is_unique() -> None:
    table = MediaAssetRow.__table__
    assert table.columns["storage_key"].unique is True


def test_image_variant_has_asset_kind_unique_constraint() -> None:
    table = ImageVariantRow.__table__
    constraint_names = {c.name for c in table.constraints}
    assert "ux_image_variant_asset_kind" in constraint_names
