/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppliancesRouteImport } from './routes/appliances'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FurnitureRouteImport } from './routes/furniture'
import { Route as HostelsRouteImport } from './routes/hostels'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as InteriorRouteImport } from './routes/interior'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LandscapeRouteImport } from './routes/landscape'
import { Route as ListRouteImport } from './routes/list'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MapRouteImport } from './routes/map'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin/feature-flags'
import { Route as AdminFormsRouteImport } from './routes/admin/forms'
import { Route as AdminListingsRouteImport } from './routes/admin/listings'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminSearchConfigRouteImport } from './routes/admin/search-config'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerificationRouteImport } from './routes/admin/verification'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsIdRouteImport } from './routes/agents/$id'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as BusinessProfileIdRouteImport } from './routes/business-profile/$id'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard/buyer'
import { Route as DashboardSellerRouteImport } from './routes/dashboard/seller'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'
import { Route as ListingsIdEditRouteImport } from './routes/listings/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliancesRoute = AppliancesRouteImport.update({
  id: '/appliances',
  path: '/appliances',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnitureRoute = FurnitureRouteImport.update({
  id: '/furniture',
  path: '/furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelsRoute = HostelsRouteImport.update({
  id: '/hostels',
  path: '/hostels',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRoute = InteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LandscapeRoute = LandscapeRouteImport.update({
  id: '/landscape',
  path: '/landscape',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/admin/forms',
  path: '/admin/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSearchConfigRoute = AdminSearchConfigRouteImport.update({
  id: '/admin/search-config',
  path: '/admin/search-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProfileIdRoute = BusinessProfileIdRouteImport.update({
  id: '/business-profile/$id',
  path: '/business-profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/dashboard/seller',
  path: '/dashboard/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdEditRoute = ListingsIdEditRouteImport.update({
  id: '/listings/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appliances': typeof AppliancesRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/furniture': typeof FurnitureRoute
  '/hostels': typeof HostelsRoute
  '/hotels': typeof HotelsRoute
  '/interior': typeof InteriorRoute
  '/jobs': typeof JobsRoute
  '/landscape': typeof LandscapeRoute
  '/list': typeof ListRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/materials': typeof MaterialsRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/search-config': typeof AdminSearchConfigRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/business-profile/$id': typeof BusinessProfileIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appliances': typeof AppliancesRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/furniture': typeof FurnitureRoute
  '/hostels': typeof HostelsRoute
  '/hotels': typeof HotelsRoute
  '/interior': typeof InteriorRoute
  '/jobs': typeof JobsRoute
  '/landscape': typeof LandscapeRoute
  '/list': typeof ListRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/materials': typeof MaterialsRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/search-config': typeof AdminSearchConfigRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/business-profile/$id': typeof BusinessProfileIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appliances': typeof AppliancesRoute
  '/blog': typeof BlogRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/furniture': typeof FurnitureRoute
  '/hostels': typeof HostelsRoute
  '/hotels': typeof HotelsRoute
  '/interior': typeof InteriorRoute
  '/jobs': typeof JobsRoute
  '/landscape': typeof LandscapeRoute
  '/list': typeof ListRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/materials': typeof MaterialsRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/search-config': typeof AdminSearchConfigRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/business-profile/$id': typeof BusinessProfileIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/listings/$id/edit': typeof ListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appliances'
    | '/blog'
    | '/checkout'
    | '/compare'
    | '/construction'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/furniture'
    | '/hostels'
    | '/hotels'
    | '/interior'
    | '/jobs'
    | '/landscape'
    | '/list'
    | '/maintenance'
    | '/map'
    | '/materials'
    | '/messages'
    | '/news'
    | '/notifications'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/security'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/support'
    | '/verification'
    | '/wallet'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/categories'
    | '/admin/config'
    | '/admin/feature-flags'
    | '/admin/forms'
    | '/admin/listings'
    | '/admin/moderation'
    | '/admin/search-config'
    | '/admin/users'
    | '/admin/verification'
    | '/agents/$id'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/business-profile/$id'
    | '/categories/$slug'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/properties/$slug'
    | '/admin/'
    | '/agents/'
    | '/categories/'
    | '/dashboard/'
    | '/properties/'
    | '/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appliances'
    | '/blog'
    | '/checkout'
    | '/compare'
    | '/construction'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/furniture'
    | '/hostels'
    | '/hotels'
    | '/interior'
    | '/jobs'
    | '/landscape'
    | '/list'
    | '/maintenance'
    | '/map'
    | '/materials'
    | '/messages'
    | '/news'
    | '/notifications'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/security'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/support'
    | '/verification'
    | '/wallet'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/categories'
    | '/admin/config'
    | '/admin/feature-flags'
    | '/admin/forms'
    | '/admin/listings'
    | '/admin/moderation'
    | '/admin/search-config'
    | '/admin/users'
    | '/admin/verification'
    | '/agents/$id'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/business-profile/$id'
    | '/categories/$slug'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/properties/$slug'
    | '/admin'
    | '/agents'
    | '/categories'
    | '/dashboard'
    | '/properties'
    | '/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appliances'
    | '/blog'
    | '/checkout'
    | '/compare'
    | '/construction'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/furniture'
    | '/hostels'
    | '/hotels'
    | '/interior'
    | '/jobs'
    | '/landscape'
    | '/list'
    | '/maintenance'
    | '/map'
    | '/materials'
    | '/messages'
    | '/news'
    | '/notifications'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/security'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/support'
    | '/verification'
    | '/wallet'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/categories'
    | '/admin/config'
    | '/admin/feature-flags'
    | '/admin/forms'
    | '/admin/listings'
    | '/admin/moderation'
    | '/admin/search-config'
    | '/admin/users'
    | '/admin/verification'
    | '/agents/$id'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/business-profile/$id'
    | '/categories/$slug'
    | '/dashboard/buyer'
    | '/dashboard/seller'
    | '/properties/$slug'
    | '/admin/'
    | '/agents/'
    | '/categories/'
    | '/dashboard/'
    | '/properties/'
    | '/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppliancesRoute: typeof AppliancesRoute
  BlogRoute: typeof BlogRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  FurnitureRoute: typeof FurnitureRoute
  HostelsRoute: typeof HostelsRoute
  HotelsRoute: typeof HotelsRoute
  InteriorRoute: typeof InteriorRoute
  JobsRoute: typeof JobsRoute
  LandscapeRoute: typeof LandscapeRoute
  ListRoute: typeof ListRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MapRoute: typeof MapRoute
  MaterialsRoute: typeof MaterialsRoute
  MessagesRoute: typeof MessagesRoute
  NewsRoute: typeof NewsRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
  VerificationRoute: typeof VerificationRoute
  WalletRoute: typeof WalletRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminSearchConfigRoute: typeof AdminSearchConfigRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AgentsIdRoute: typeof AgentsIdRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BusinessProfileIdRoute: typeof BusinessProfileIdRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardSellerRoute: typeof DashboardSellerRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ListingsIdEditRoute: typeof ListingsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appliances': {
      id: '/appliances'
      path: '/appliances'
      fullPath: '/appliances'
      preLoaderRoute: typeof AppliancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furniture': {
      id: '/furniture'
      path: '/furniture'
      fullPath: '/furniture'
      preLoaderRoute: typeof FurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostels': {
      id: '/hostels'
      path: '/hostels'
      fullPath: '/hostels'
      preLoaderRoute: typeof HostelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior': {
      id: '/interior'
      path: '/interior'
      fullPath: '/interior'
      preLoaderRoute: typeof InteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landscape': {
      id: '/landscape'
      path: '/landscape'
      fullPath: '/landscape'
      preLoaderRoute: typeof LandscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/admin/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/search-config': {
      id: '/admin/search-config'
      path: '/admin/search-config'
      fullPath: '/admin/search-config'
      preLoaderRoute: typeof AdminSearchConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-profile/$id': {
      id: '/business-profile/$id'
      path: '/business-profile/$id'
      fullPath: '/business-profile/$id'
      preLoaderRoute: typeof BusinessProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/dashboard/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id/edit': {
      id: '/listings/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/listings/$id/edit'
      preLoaderRoute: typeof ListingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppliancesRoute: AppliancesRoute,
  BlogRoute: BlogRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  FurnitureRoute: FurnitureRoute,
  HostelsRoute: HostelsRoute,
  HotelsRoute: HotelsRoute,
  InteriorRoute: InteriorRoute,
  JobsRoute: JobsRoute,
  LandscapeRoute: LandscapeRoute,
  ListRoute: ListRoute,
  MaintenanceRoute: MaintenanceRoute,
  MapRoute: MapRoute,
  MaterialsRoute: MaterialsRoute,
  MessagesRoute: MessagesRoute,
  NewsRoute: NewsRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
  VerificationRoute: VerificationRoute,
  WalletRoute: WalletRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminSearchConfigRoute: AdminSearchConfigRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AgentsIdRoute: AgentsIdRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BusinessProfileIdRoute: BusinessProfileIdRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardSellerRoute: DashboardSellerRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ListingsIdEditRoute: ListingsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
