/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdRulesRouteImport } from './routes/ad-rules'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AppliancesRouteImport } from './routes/appliances'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BossRouteImport } from './routes/boss'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FurnitureRouteImport } from './routes/furniture'
import { Route as HostelsRouteImport } from './routes/hostels'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as InteriorRouteImport } from './routes/interior'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LandscapeRouteImport } from './routes/landscape'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MapRouteImport } from './routes/map'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PublicOfferRouteImport } from './routes/public-offer'
import { Route as RecreationRouteImport } from './routes/recreation'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SecurityPolicyRouteImport } from './routes/security-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as OwnerAdminSlugIndexRouteImport } from './routes/$ownerAdminSlug/index'
import { Route as OwnerAdminSlugBannersRouteImport } from './routes/$ownerAdminSlug/banners'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsIdRouteImport } from './routes/agents/$id'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesSplatRouteImport } from './routes/categories/$'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesProfileIdRouteImport } from './routes/companies/$profileId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardBusinessProfileRouteImport } from './routes/dashboard/business-profile'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard/buyer'
import { Route as DashboardInvestorRouteImport } from './routes/dashboard/investor'
import { Route as DashboardSellerRouteImport } from './routes/dashboard/seller'
import { Route as InvestIndexRouteImport } from './routes/invest/index'
import { Route as InvestSlugRouteImport } from './routes/invest/$slug'
import { Route as ListIndexRouteImport } from './routes/list/index'
import { Route as ListListingIdRouteImport } from './routes/list/$listingId'
import { Route as ListingListingIdRouteImport } from './routes/listing/$listingId'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'
import { Route as AuthCallbackAppleRouteImport } from './routes/auth/callback/apple'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth/callback/google'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdRulesRoute = AdRulesRouteImport.update({
  id: '/ad-rules',
  path: '/ad-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliancesRoute = AppliancesRouteImport.update({
  id: '/appliances',
  path: '/appliances',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BossRoute = BossRouteImport.update({
  id: '/boss',
  path: '/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnitureRoute = FurnitureRouteImport.update({
  id: '/furniture',
  path: '/furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelsRoute = HostelsRouteImport.update({
  id: '/hostels',
  path: '/hostels',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRoute = InteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LandscapeRoute = LandscapeRouteImport.update({
  id: '/landscape',
  path: '/landscape',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOfferRoute = PublicOfferRouteImport.update({
  id: '/public-offer',
  path: '/public-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const RecreationRoute = RecreationRouteImport.update({
  id: '/recreation',
  path: '/recreation',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPolicyRoute = SecurityPolicyRouteImport.update({
  id: '/security-policy',
  path: '/security-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAdminSlugIndexRoute = OwnerAdminSlugIndexRouteImport.update({
  id: '/$ownerAdminSlug/',
  path: '/$ownerAdminSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAdminSlugBannersRoute = OwnerAdminSlugBannersRouteImport.update({
  id: '/$ownerAdminSlug/banners',
  path: '/$ownerAdminSlug/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSplatRoute = CategoriesSplatRouteImport.update({
  id: '/categories/$',
  path: '/categories/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesProfileIdRoute = CompaniesProfileIdRouteImport.update({
  id: '/companies/$profileId',
  path: '/companies/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessProfileRoute =
  DashboardBusinessProfileRouteImport.update({
    id: '/dashboard/business-profile',
    path: '/dashboard/business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestorRoute = DashboardInvestorRouteImport.update({
  id: '/dashboard/investor',
  path: '/dashboard/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/dashboard/seller',
  path: '/dashboard/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestIndexRoute = InvestIndexRouteImport.update({
  id: '/invest/',
  path: '/invest/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestSlugRoute = InvestSlugRouteImport.update({
  id: '/invest/$slug',
  path: '/invest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListIndexRoute = ListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListingIdRoute = ListListingIdRouteImport.update({
  id: '/list/$listingId',
  path: '/list/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingListingIdRoute = ListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackAppleRoute = AuthCallbackAppleRouteImport.update({
  id: '/auth/callback/apple',
  path: '/auth/callback/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ad-rules': typeof AdRulesRoute
  '/ai': typeof AiRoute
  '/appliances': typeof AppliancesRoute
  '/blog': typeof BlogRoute
  '/boss': typeof BossRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/furniture': typeof FurnitureRoute
  '/hostels': typeof HostelsRoute
  '/hotels': typeof HotelsRoute
  '/interior': typeof InteriorRoute
  '/jobs': typeof JobsRoute
  '/landscape': typeof LandscapeRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/materials': typeof MaterialsRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/offer': typeof OfferRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/public-offer': typeof PublicOfferRoute
  '/recreation': typeof RecreationRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rules': typeof RulesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/$ownerAdminSlug/banners': typeof OwnerAdminSlugBannersRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/companies/$profileId': typeof CompaniesProfileIdRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/invest/$slug': typeof InvestSlugRoute
  '/list/$listingId': typeof ListListingIdRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/$ownerAdminSlug/': typeof OwnerAdminSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/invest/': typeof InvestIndexRoute
  '/list/': typeof ListIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/auth/callback/apple': typeof AuthCallbackAppleRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ad-rules': typeof AdRulesRoute
  '/ai': typeof AiRoute
  '/appliances': typeof AppliancesRoute
  '/blog': typeof BlogRoute
  '/boss': typeof BossRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/furniture': typeof FurnitureRoute
  '/hostels': typeof HostelsRoute
  '/hotels': typeof HotelsRoute
  '/interior': typeof InteriorRoute
  '/jobs': typeof JobsRoute
  '/landscape': typeof LandscapeRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/materials': typeof MaterialsRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/offer': typeof OfferRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/public-offer': typeof PublicOfferRoute
  '/recreation': typeof RecreationRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rules': typeof RulesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/$ownerAdminSlug/banners': typeof OwnerAdminSlugBannersRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/companies/$profileId': typeof CompaniesProfileIdRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/invest/$slug': typeof InvestSlugRoute
  '/list/$listingId': typeof ListListingIdRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/$ownerAdminSlug': typeof OwnerAdminSlugIndexRoute
  '/admin': typeof AdminIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/invest': typeof InvestIndexRoute
  '/list': typeof ListIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/auth/callback/apple': typeof AuthCallbackAppleRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ad-rules': typeof AdRulesRoute
  '/ai': typeof AiRoute
  '/appliances': typeof AppliancesRoute
  '/blog': typeof BlogRoute
  '/boss': typeof BossRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/furniture': typeof FurnitureRoute
  '/hostels': typeof HostelsRoute
  '/hotels': typeof HotelsRoute
  '/interior': typeof InteriorRoute
  '/jobs': typeof JobsRoute
  '/landscape': typeof LandscapeRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/materials': typeof MaterialsRoute
  '/messages': typeof MessagesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/offer': typeof OfferRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/public-offer': typeof PublicOfferRoute
  '/recreation': typeof RecreationRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rules': typeof RulesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/$ownerAdminSlug/banners': typeof OwnerAdminSlugBannersRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/companies/$profileId': typeof CompaniesProfileIdRoute
  '/dashboard/business-profile': typeof DashboardBusinessProfileRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/investor': typeof DashboardInvestorRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/invest/$slug': typeof InvestSlugRoute
  '/list/$listingId': typeof ListListingIdRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/$ownerAdminSlug/': typeof OwnerAdminSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/invest/': typeof InvestIndexRoute
  '/list/': typeof ListIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/auth/callback/apple': typeof AuthCallbackAppleRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ad-rules'
    | '/ai'
    | '/appliances'
    | '/blog'
    | '/boss'
    | '/checkout'
    | '/compare'
    | '/construction'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/furniture'
    | '/hostels'
    | '/hotels'
    | '/interior'
    | '/jobs'
    | '/landscape'
    | '/maintenance'
    | '/map'
    | '/materials'
    | '/messages'
    | '/news'
    | '/notifications'
    | '/offer'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/public-offer'
    | '/recreation'
    | '/refund'
    | '/refund-policy'
    | '/rules'
    | '/saved'
    | '/search'
    | '/security'
    | '/security-policy'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/support'
    | '/terms'
    | '/verification'
    | '/wallet'
    | '/$ownerAdminSlug/banners'
    | '/admin/companies'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/users'
    | '/agents/$id'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$'
    | '/companies/$profileId'
    | '/dashboard/business-profile'
    | '/dashboard/buyer'
    | '/dashboard/investor'
    | '/dashboard/seller'
    | '/invest/$slug'
    | '/list/$listingId'
    | '/listing/$listingId'
    | '/properties/$slug'
    | '/$ownerAdminSlug/'
    | '/admin/'
    | '/agents/'
    | '/categories/'
    | '/companies/'
    | '/dashboard/'
    | '/invest/'
    | '/list/'
    | '/properties/'
    | '/auth/callback/apple'
    | '/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ad-rules'
    | '/ai'
    | '/appliances'
    | '/blog'
    | '/boss'
    | '/checkout'
    | '/compare'
    | '/construction'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/furniture'
    | '/hostels'
    | '/hotels'
    | '/interior'
    | '/jobs'
    | '/landscape'
    | '/maintenance'
    | '/map'
    | '/materials'
    | '/messages'
    | '/news'
    | '/notifications'
    | '/offer'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/public-offer'
    | '/recreation'
    | '/refund'
    | '/refund-policy'
    | '/rules'
    | '/saved'
    | '/search'
    | '/security'
    | '/security-policy'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/support'
    | '/terms'
    | '/verification'
    | '/wallet'
    | '/$ownerAdminSlug/banners'
    | '/admin/companies'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/users'
    | '/agents/$id'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$'
    | '/companies/$profileId'
    | '/dashboard/business-profile'
    | '/dashboard/buyer'
    | '/dashboard/investor'
    | '/dashboard/seller'
    | '/invest/$slug'
    | '/list/$listingId'
    | '/listing/$listingId'
    | '/properties/$slug'
    | '/$ownerAdminSlug'
    | '/admin'
    | '/agents'
    | '/categories'
    | '/companies'
    | '/dashboard'
    | '/invest'
    | '/list'
    | '/properties'
    | '/auth/callback/apple'
    | '/auth/callback/google'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ad-rules'
    | '/ai'
    | '/appliances'
    | '/blog'
    | '/boss'
    | '/checkout'
    | '/compare'
    | '/construction'
    | '/contact'
    | '/faq'
    | '/favorites'
    | '/furniture'
    | '/hostels'
    | '/hotels'
    | '/interior'
    | '/jobs'
    | '/landscape'
    | '/maintenance'
    | '/map'
    | '/materials'
    | '/messages'
    | '/news'
    | '/notifications'
    | '/offer'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/public-offer'
    | '/recreation'
    | '/refund'
    | '/refund-policy'
    | '/rules'
    | '/saved'
    | '/search'
    | '/security'
    | '/security-policy'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/support'
    | '/terms'
    | '/verification'
    | '/wallet'
    | '/$ownerAdminSlug/banners'
    | '/admin/companies'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/users'
    | '/agents/$id'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/categories/$'
    | '/companies/$profileId'
    | '/dashboard/business-profile'
    | '/dashboard/buyer'
    | '/dashboard/investor'
    | '/dashboard/seller'
    | '/invest/$slug'
    | '/list/$listingId'
    | '/listing/$listingId'
    | '/properties/$slug'
    | '/$ownerAdminSlug/'
    | '/admin/'
    | '/agents/'
    | '/categories/'
    | '/companies/'
    | '/dashboard/'
    | '/invest/'
    | '/list/'
    | '/properties/'
    | '/auth/callback/apple'
    | '/auth/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdRulesRoute: typeof AdRulesRoute
  AiRoute: typeof AiRoute
  AppliancesRoute: typeof AppliancesRoute
  BlogRoute: typeof BlogRoute
  BossRoute: typeof BossRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  FurnitureRoute: typeof FurnitureRoute
  HostelsRoute: typeof HostelsRoute
  HotelsRoute: typeof HotelsRoute
  InteriorRoute: typeof InteriorRoute
  JobsRoute: typeof JobsRoute
  LandscapeRoute: typeof LandscapeRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MapRoute: typeof MapRoute
  MaterialsRoute: typeof MaterialsRoute
  MessagesRoute: typeof MessagesRoute
  NewsRoute: typeof NewsRoute
  NotificationsRoute: typeof NotificationsRoute
  OfferRoute: typeof OfferRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicOfferRoute: typeof PublicOfferRoute
  RecreationRoute: typeof RecreationRoute
  RefundRoute: typeof RefundRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RulesRoute: typeof RulesRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SecurityPolicyRoute: typeof SecurityPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
  WalletRoute: typeof WalletRoute
  OwnerAdminSlugBannersRoute: typeof OwnerAdminSlugBannersRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AgentsIdRoute: typeof AgentsIdRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CategoriesSplatRoute: typeof CategoriesSplatRoute
  CompaniesProfileIdRoute: typeof CompaniesProfileIdRoute
  DashboardBusinessProfileRoute: typeof DashboardBusinessProfileRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardInvestorRoute: typeof DashboardInvestorRoute
  DashboardSellerRoute: typeof DashboardSellerRoute
  InvestSlugRoute: typeof InvestSlugRoute
  ListListingIdRoute: typeof ListListingIdRoute
  ListingListingIdRoute: typeof ListingListingIdRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  OwnerAdminSlugIndexRoute: typeof OwnerAdminSlugIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  InvestIndexRoute: typeof InvestIndexRoute
  ListIndexRoute: typeof ListIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  AuthCallbackAppleRoute: typeof AuthCallbackAppleRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-rules': {
      id: '/ad-rules'
      path: '/ad-rules'
      fullPath: '/ad-rules'
      preLoaderRoute: typeof AdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appliances': {
      id: '/appliances'
      path: '/appliances'
      fullPath: '/appliances'
      preLoaderRoute: typeof AppliancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss': {
      id: '/boss'
      path: '/boss'
      fullPath: '/boss'
      preLoaderRoute: typeof BossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furniture': {
      id: '/furniture'
      path: '/furniture'
      fullPath: '/furniture'
      preLoaderRoute: typeof FurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostels': {
      id: '/hostels'
      path: '/hostels'
      fullPath: '/hostels'
      preLoaderRoute: typeof HostelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior': {
      id: '/interior'
      path: '/interior'
      fullPath: '/interior'
      preLoaderRoute: typeof InteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landscape': {
      id: '/landscape'
      path: '/landscape'
      fullPath: '/landscape'
      preLoaderRoute: typeof LandscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-offer': {
      id: '/public-offer'
      path: '/public-offer'
      fullPath: '/public-offer'
      preLoaderRoute: typeof PublicOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recreation': {
      id: '/recreation'
      path: '/recreation'
      fullPath: '/recreation'
      preLoaderRoute: typeof RecreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-policy': {
      id: '/security-policy'
      path: '/security-policy'
      fullPath: '/security-policy'
      preLoaderRoute: typeof SecurityPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$ownerAdminSlug/': {
      id: '/$ownerAdminSlug/'
      path: '/$ownerAdminSlug'
      fullPath: '/$ownerAdminSlug/'
      preLoaderRoute: typeof OwnerAdminSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$ownerAdminSlug/banners': {
      id: '/$ownerAdminSlug/banners'
      path: '/$ownerAdminSlug/banners'
      fullPath: '/$ownerAdminSlug/banners'
      preLoaderRoute: typeof OwnerAdminSlugBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$': {
      id: '/categories/$'
      path: '/categories/$'
      fullPath: '/categories/$'
      preLoaderRoute: typeof CategoriesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$profileId': {
      id: '/companies/$profileId'
      path: '/companies/$profileId'
      fullPath: '/companies/$profileId'
      preLoaderRoute: typeof CompaniesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business-profile': {
      id: '/dashboard/business-profile'
      path: '/dashboard/business-profile'
      fullPath: '/dashboard/business-profile'
      preLoaderRoute: typeof DashboardBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/investor': {
      id: '/dashboard/investor'
      path: '/dashboard/investor'
      fullPath: '/dashboard/investor'
      preLoaderRoute: typeof DashboardInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/dashboard/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/': {
      id: '/invest/'
      path: '/invest'
      fullPath: '/invest/'
      preLoaderRoute: typeof InvestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/$slug': {
      id: '/invest/$slug'
      path: '/invest/$slug'
      fullPath: '/invest/$slug'
      preLoaderRoute: typeof InvestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/': {
      id: '/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof ListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listingId': {
      id: '/list/$listingId'
      path: '/list/$listingId'
      fullPath: '/list/$listingId'
      preLoaderRoute: typeof ListListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$listingId': {
      id: '/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/listing/$listingId'
      preLoaderRoute: typeof ListingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/apple': {
      id: '/auth/callback/apple'
      path: '/auth/callback/apple'
      fullPath: '/auth/callback/apple'
      preLoaderRoute: typeof AuthCallbackAppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdRulesRoute: AdRulesRoute,
  AiRoute: AiRoute,
  AppliancesRoute: AppliancesRoute,
  BlogRoute: BlogRoute,
  BossRoute: BossRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  FurnitureRoute: FurnitureRoute,
  HostelsRoute: HostelsRoute,
  HotelsRoute: HotelsRoute,
  InteriorRoute: InteriorRoute,
  JobsRoute: JobsRoute,
  LandscapeRoute: LandscapeRoute,
  MaintenanceRoute: MaintenanceRoute,
  MapRoute: MapRoute,
  MaterialsRoute: MaterialsRoute,
  MessagesRoute: MessagesRoute,
  NewsRoute: NewsRoute,
  NotificationsRoute: NotificationsRoute,
  OfferRoute: OfferRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PublicOfferRoute: PublicOfferRoute,
  RecreationRoute: RecreationRoute,
  RefundRoute: RefundRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RulesRoute: RulesRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SecurityPolicyRoute: SecurityPolicyRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
  WalletRoute: WalletRoute,
  OwnerAdminSlugBannersRoute: OwnerAdminSlugBannersRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AgentsIdRoute: AgentsIdRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CategoriesSplatRoute: CategoriesSplatRoute,
  CompaniesProfileIdRoute: CompaniesProfileIdRoute,
  DashboardBusinessProfileRoute: DashboardBusinessProfileRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardInvestorRoute: DashboardInvestorRoute,
  DashboardSellerRoute: DashboardSellerRoute,
  InvestSlugRoute: InvestSlugRoute,
  ListListingIdRoute: ListListingIdRoute,
  ListingListingIdRoute: ListingListingIdRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  OwnerAdminSlugIndexRoute: OwnerAdminSlugIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  InvestIndexRoute: InvestIndexRoute,
  ListIndexRoute: ListIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  AuthCallbackAppleRoute: AuthCallbackAppleRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
